"""empty message

Revision ID: 39782036965d
Revises: 
Create Date: 2020-01-28 11:27:12.082628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39782036965d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('album',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('album_name', sa.String(length=20), nullable=False),
    sa.Column('album_type', sa.String(length=20), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('album_name')
    )
    op.create_table('pics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pic_name', sa.String(length=20), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=True),
    sa.Column('trashed', sa.Boolean(), nullable=True),
    sa.Column('uploaded_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.Column('profile_pic', sa.String(length=200), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('public_id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('pics')
    op.drop_table('album')
    # ### end Alembic commands ###
